<?php

// 500 — server error / fail and try again

return [
    [
        'text' => 'Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.',
        'author' => 'Samuel Beckett',
        'source' => 'Worstward Ho',
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Failing again isn\'t the end of the process — it\'s just another lap of it.',
    ],
    [
        'text' => 'I have not failed. I\'ve just found 10,000 ways that won\'t work.',
        'author' => 'Thomas A. Edison',
        'source' => null,
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Every attempt that didn\'t work still counted for something.',
    ],
    [
        'text' => 'The world breaks everyone, and afterward, many are strong at the broken places.',
        'author' => 'Ernest Hemingway',
        'source' => 'A Farewell to Arms',
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'The broken places have a way of becoming the strongest ones.',
    ],
    [
        'text' => 'Our greatest glory is not in never falling, but in rising every time we fall.',
        'author' => 'Confucius',
        'source' => null,
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Falling isn\'t really the failure — staying down would be.',
    ],
    [
        'text' => 'I\'ve failed over and over and over again in my life and that is why I succeed.',
        'author' => 'Michael Jordan',
        'source' => null,
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'All those failed attempts, somehow, are exactly what got here in the end.',
    ],
    [
        'text' => 'Success is not final, failure is not fatal: it is the courage to continue that counts.',
        'author' => 'Winston Churchill',
        'source' => null,
        'lang' => 'en',
        'genre' => 'formal',
        'meaning' => 'Success passes, failure passes — what stays is whether we kept going.',
    ],
    [
        'text' => 'It\'s not a bug, it\'s an unexpected feature.',
        'author' => 'Pepatah Programmer',
        'source' => null,
        'lang' => 'en',
        'genre' => 'humor',
        'meaning' => 'Every error is just a feature that hasn\'t been documented yet.',
    ],
    [
        'text' => 'Setiap sistem yang tumbuh pasti pernah rebah; yang penting bangun lagi.',
        'author' => 'Anonymous',
        'source' => null,
        'lang' => 'id',
        'genre' => 'wise',
        'meaning' => 'Sistem yang tumbuh memang sesekali rebah — yang penting tahu caranya bangun lagi.',
    ],
    [
        'text' => 'Bukan kamu yang error, ini kami. Lagi proses insaf.',
        'author' => 'Anonymous',
        'source' => null,
        'lang' => 'id',
        'genre' => 'humor',
        'meaning' => 'Yang error bukan kamu kok — ini memang lagi proses insaf sendiri.',
    ],
    [
        'text' => 'Errornya bukan kiamat, cuma server lagi drama sebentar.',
        'author' => 'Anonymous',
        'source' => null,
        'lang' => 'id',
        'genre' => 'humor',
        'meaning' => 'Bukan kiamat, cuma drama sesaat yang kebetulan muncul di waktu yang salah.',
    ],
];
