<?php

// 500 — server error / fail and try again

return [
    [
        'text' => 'Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.',
        'author' => 'Samuel Beckett',
        'source' => 'Worstward Ho',
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Frames repeated failure as part of a process rather than a stopping point.',
    ],
    [
        'text' => 'I have not failed. I\'ve just found 10,000 ways that won\'t work.',
        'author' => 'Thomas A. Edison',
        'source' => null,
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Reframes failed attempts as information gathered along the way.',
    ],
    [
        'text' => 'The world breaks everyone, and afterward, many are strong at the broken places.',
        'author' => 'Ernest Hemingway',
        'source' => 'A Farewell to Arms',
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Observes that difficulty can also be where resilience develops.',
    ],
    [
        'text' => 'Our greatest glory is not in never falling, but in rising every time we fall.',
        'author' => 'Confucius',
        'source' => null,
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Suggests that recovering from setbacks matters more than avoiding them entirely.',
    ],
    [
        'text' => 'I\'ve failed over and over and over again in my life and that is why I succeed.',
        'author' => 'Michael Jordan',
        'source' => null,
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Connects repeated failure directly to eventual success.',
    ],
    [
        'text' => 'Success is not final, failure is not fatal: it is the courage to continue that counts.',
        'author' => 'Winston Churchill',
        'source' => null,
        'lang' => 'en',
        'genre' => 'formal',
        'meaning' => 'Frames both success and failure as temporary, with persistence as the constant.',
    ],
    [
        'text' => 'It\'s not a bug, it\'s an unexpected feature.',
        'author' => 'Pepatah Programmer',
        'source' => null,
        'lang' => 'en',
        'genre' => 'humor',
        'meaning' => 'A common programmer joke that reframes an error as an unplanned feature.',
    ],
    [
        'text' => 'Setiap sistem yang tumbuh pasti pernah rebah; yang penting bangun lagi.',
        'author' => 'Anonymous',
        'source' => null,
        'lang' => 'id',
        'genre' => 'wise',
        'meaning' => 'Menyamakan gangguan sistem dengan proses wajar dalam pertumbuhan apa pun.',
    ],
    [
        'text' => 'Telah terjadi kesalahan pada sistem kami. Tim teknis sedang menanganinya.',
        'author' => 'Anonymous',
        'source' => null,
        'lang' => 'id',
        'genre' => 'formal',
        'meaning' => 'Pemberitahuan resmi bahwa terjadi kesalahan sistem dan sedang ditangani.',
    ],
    [
        'text' => 'Bukan kamu yang error, ini kami. Lagi proses insaf.',
        'author' => 'Anonymous',
        'source' => null,
        'lang' => 'id',
        'genre' => 'humor',
        'meaning' => 'Menegaskan dengan nada santai bahwa kesalahan berasal dari sistem, bukan pengguna.',
    ],
    [
        'text' => 'Errornya bukan kiamat, cuma server lagi drama sebentar.',
        'author' => 'Anonymous',
        'source' => null,
        'lang' => 'id',
        'genre' => 'humor',
        'meaning' => 'Meredakan kepanikan atas error dengan mengecilkan skalanya.',
    ],
];
