<?php

// Fallback for any other status code that doesn't have its own group.

return [
    [
        'text' => 'It does not do to dwell on dreams and forget to live.',
        'author' => 'J.K. Rowling',
        'source' => 'Harry Potter and the Philosopher\'s Stone',
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Cautions against focusing so much on wishes that present action is neglected.',
    ],
    [
        'text' => 'You are braver than you believe, stronger than you seem, and smarter than you think.',
        'author' => 'A.A. Milne',
        'source' => 'Winnie-the-Pooh',
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'An encouraging remark about underestimated personal strength.',
    ],
    [
        'text' => 'It is only with the heart that one can see rightly; what is essential is invisible to the eye.',
        'author' => 'Antoine de Saint-Exupéry',
        'source' => 'The Little Prince',
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Suggests that some things are better understood through feeling than through direct observation.',
    ],
    [
        'text' => 'Out of suffering have emerged the strongest souls.',
        'author' => 'Kahlil Gibran',
        'source' => 'The Prophet',
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Connects difficult experience with the development of resilience.',
    ],
    [
        'text' => 'The secret of getting ahead is getting started.',
        'author' => 'Mark Twain',
        'source' => null,
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Frames starting a task as the main obstacle to progress.',
    ],
    [
        'text' => 'It is hard to fail, but it is worse never to have tried to succeed.',
        'author' => 'Theodore Roosevelt',
        'source' => null,
        'lang' => 'en',
        'genre' => 'formal',
        'meaning' => 'Compares the discomfort of failing with the cost of not attempting at all.',
    ],
    [
        'text' => 'Well, this is embarrassing.',
        'author' => 'Pepatah Internet',
        'source' => null,
        'lang' => 'en',
        'genre' => 'humor',
        'meaning' => 'A common lighthearted phrase used to acknowledge something going wrong.',
    ],
    [
        'text' => 'Bermimpilah, karena Tuhan akan memeluk mimpi-mimpi itu.',
        'author' => 'Andrea Hirata',
        'source' => 'Laskar Pelangi',
        'lang' => 'id',
        'genre' => 'wise',
        'meaning' => 'Mendorong untuk tetap memiliki harapan meskipun keadaan belum sesuai rencana.',
    ],
    [
        'text' => 'Aku ingin hidup seribu tahun lagi.',
        'author' => 'Chairil Anwar',
        'source' => 'Aku',
        'lang' => 'id',
        'genre' => 'wise',
        'meaning' => 'Baris penutup puisi "Aku" yang mengungkapkan keinginan kuat untuk terus ada dan berkarya.',
    ],
    [
        'text' => 'Gantungkan cita-citamu setinggi langit.',
        'author' => 'Soekarno',
        'source' => null,
        'lang' => 'id',
        'genre' => 'formal',
        'meaning' => 'Ajakan untuk menetapkan tujuan yang tinggi dan berani.',
    ],
    [
        'text' => 'Bukan kiamat, cuma error. Ambil napas, lalu coba lagi.',
        'author' => 'Anonymous',
        'source' => null,
        'lang' => 'id',
        'genre' => 'humor',
        'meaning' => 'Menenangkan pengguna bahwa error yang terjadi bukan masalah besar.',
    ],
    [
        'text' => 'Errornya kecil, drama-nya aja yang gedean.',
        'author' => 'Anonymous',
        'source' => null,
        'lang' => 'id',
        'genre' => 'humor',
        'meaning' => 'Meredakan kesan bahwa error yang terjadi lebih serius dari kenyataannya.',
    ],
];
