<?php

// Fallback for any other status code that doesn't have its own group.

return [
    [
        'text' => 'It does not do to dwell on dreams and forget to live.',
        'author' => 'J.K. Rowling',
        'source' => 'Harry Potter and the Philosopher\'s Stone',
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Dwelling too long on what could be tends to cost what\'s happening right now.',
    ],
    [
        'text' => 'You are braver than you believe, stronger than you seem, and smarter than you think.',
        'author' => 'A.A. Milne',
        'source' => 'Winnie-the-Pooh',
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'More strength than expected usually shows up exactly when it\'s needed.',
    ],
    [
        'text' => 'It is only with the heart that one can see rightly; what is essential is invisible to the eye.',
        'author' => 'Antoine de Saint-Exupéry',
        'source' => 'The Little Prince',
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'Some things only make sense once you stop trying to just look at them.',
    ],
    [
        'text' => 'Out of suffering have emerged the strongest souls.',
        'author' => 'Kahlil Gibran',
        'source' => 'The Prophet',
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'The hardest stretches tend to be where the strongest souls were shaped.',
    ],
    [
        'text' => 'The secret of getting ahead is getting started.',
        'author' => 'Mark Twain',
        'source' => null,
        'lang' => 'en',
        'genre' => 'wise',
        'meaning' => 'The hardest part of any of this was probably just starting it.',
    ],
    [
        'text' => 'It is hard to fail, but it is worse never to have tried to succeed.',
        'author' => 'Theodore Roosevelt',
        'source' => null,
        'lang' => 'en',
        'genre' => 'formal',
        'meaning' => 'Failing stings less, in the end, than never having tried at all.',
    ],
    [
        'text' => 'Well, this is embarrassing.',
        'author' => 'Pepatah Internet',
        'source' => null,
        'lang' => 'en',
        'genre' => 'humor',
        'meaning' => 'Sometimes the only honest thing to say is exactly this.',
    ],
    [
        'text' => 'Bermimpilah, karena Tuhan akan memeluk mimpi-mimpi itu.',
        'author' => 'Andrea Hirata',
        'source' => 'Laskar Pelangi',
        'lang' => 'id',
        'genre' => 'wise',
        'meaning' => 'Mimpi itu tetap layak dipegang, bahkan waktu keadaan belum sesuai rencana.',
    ],
    [
        'text' => 'Aku ingin hidup seribu tahun lagi.',
        'author' => 'Chairil Anwar',
        'source' => 'Aku',
        'lang' => 'id',
        'genre' => 'wise',
        'meaning' => 'Sekali hidup, rasanya memang ingin terus ada dan terus berkarya.',
    ],
    [
        'text' => 'Gantungkan cita-citamu setinggi langit.',
        'author' => 'Soekarno',
        'source' => null,
        'lang' => 'id',
        'genre' => 'formal',
        'meaning' => 'Cita-cita yang tinggi itu memang pantas digantungkan setinggi langit.',
    ],
    [
        'text' => 'Bukan kiamat, cuma error. Ambil napas, lalu coba lagi.',
        'author' => 'Anonymous',
        'source' => null,
        'lang' => 'id',
        'genre' => 'humor',
        'meaning' => 'Bukan kiamat kok, cuma error kecil yang kebetulan lewat.',
    ],
    [
        'text' => 'Errornya kecil, drama-nya aja yang gedean.',
        'author' => 'Anonymous',
        'source' => null,
        'lang' => 'id',
        'genre' => 'humor',
        'meaning' => 'Errornya kecil — cuma dramanya saja yang kelihatan lebih besar dari aslinya.',
    ],
];
